baseURL = 'http://priyanshoon.xyz/'
languageCode = 'en-us'
title = 'Priyanshoon'
theme = 'etch'
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "My internet corner"
  copyright = "Copyright © 2023 priyanshoon.xyz"
  dark = "auto"
  highlight = true


[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

  [[menu.main]]
    identifier = "contact"
    name = "contact"
    title = "contact"
    url = "/contact/"
    weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true
